"""add_api_keys_table

Revision ID: 5bfcdac263f5
Revises: 6ff634bb758e
Create Date: 2025-12-03 18:41:41.199063
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5bfcdac263f5"
down_revision: Union[str, None] = "6ff634bb758e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
