"""add_template_metadata_fields

Revision ID: 4bcc57c893f5
Revises: add_templates
Create Date: 2025-12-05 15:31:39.788359
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bcc57c893f5'
down_revision: Union[str, None] = 'add_templates'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_slides_template_id'), table_name='template_slides')

    # Add columns as nullable first to handle existing data
    op.add_column('templates', sa.Column('difficulty_level', sa.String(length=20), nullable=True))
    op.add_column('templates', sa.Column('estimated_time', sa.Integer(), nullable=True))
    op.add_column('templates', sa.Column('industry_tags', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('templates', sa.Column('popularity_score', sa.Integer(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE templates SET difficulty_level = 'beginner' WHERE difficulty_level IS NULL")
    op.execute("UPDATE templates SET estimated_time = 10 WHERE estimated_time IS NULL")
    op.execute("UPDATE templates SET popularity_score = 0 WHERE popularity_score IS NULL")

    # Now make required columns NOT NULL
    op.alter_column('templates', 'difficulty_level', nullable=False)
    op.alter_column('templates', 'estimated_time', nullable=False)
    op.alter_column('templates', 'popularity_score', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'popularity_score')
    op.drop_column('templates', 'industry_tags')
    op.drop_column('templates', 'estimated_time')
    op.drop_column('templates', 'difficulty_level')
    op.create_index(op.f('ix_template_slides_template_id'), 'template_slides', ['template_id'], unique=False)
    # ### end Alembic commands ###
