"""
System template definitions for seeding the database
"""

SYSTEM_TEMPLATES = [
    {
        "name": "Startup Pitch Deck",
        "description": "Classic 10-slide pitch deck for investors",
        "category": "business",
        "theme": "sunset",
        "tags": ["startup", "investor", "funding", "pitch"],
        "difficulty_level": "intermediate",
        "estimated_time": 15,
        "industry_tags": ["startups", "venture-capital", "technology"],
        "popularity_score": 100,
        "slides": [
            {
                "order": 1,
                "slide_type": "title",
                "ai_instructions": "Company name and compelling tagline",
            },
            {
                "order": 2,
                "slide_type": "content",
                "placeholder_title": "The Problem",
                "ai_instructions": "Describe the specific pain point in 50-80 words. Include: 1) who experiences it, 2) frequency/severity, 3) current inadequate solutions. Use data if available.",
            },
            {
                "order": 3,
                "slide_type": "content",
                "placeholder_title": "Our Solution",
                "ai_instructions": "Explain the product/service in 60-100 words. Focus on: 1) how it solves the problem uniquely, 2) key differentiator, 3) simple value proposition. Avoid jargon.",
            },
            {
                "order": 4,
                "slide_type": "big_number",
                "placeholder_title": "Market Opportunity",
                "ai_instructions": "TAM/SAM/SOM with impressive numbers",
            },
            {
                "order": 5,
                "slide_type": "bullets",
                "placeholder_title": "Business Model",
                "ai_instructions": "Revenue streams and pricing",
            },
            {
                "order": 6,
                "slide_type": "chart",
                "placeholder_title": "Traction",
                "ai_instructions": "Growth metrics chart",
            },
            {
                "order": 7,
                "slide_type": "comparison",
                "placeholder_title": "Competitive Advantage",
                "ai_instructions": "Us vs competitors",
            },
            {
                "order": 8,
                "slide_type": "timeline",
                "placeholder_title": "Roadmap",
                "ai_instructions": "Key milestones",
            },
            {
                "order": 9,
                "slide_type": "stats",
                "placeholder_title": "The Team",
                "ai_instructions": "Key team members",
            },
            {
                "order": 10,
                "slide_type": "section",
                "placeholder_title": "The Ask",
                "ai_instructions": "Funding amount and use",
            },
        ],
    },
    {
        "name": "Quarterly Business Review",
        "description": "Comprehensive quarterly performance report",
        "category": "business",
        "theme": "ocean",
        "tags": ["quarterly", "report", "performance", "metrics"],
        "difficulty_level": "beginner",
        "estimated_time": 12,
        "industry_tags": ["business", "corporate", "management"],
        "popularity_score": 85,
        "slides": [
            {
                "order": 1,
                "slide_type": "title",
                "ai_instructions": "Quarter and year with company name",
            },
            {
                "order": 2,
                "slide_type": "stats",
                "placeholder_title": "Key Metrics",
                "ai_instructions": "Top 4 KPIs for the quarter",
            },
            {
                "order": 3,
                "slide_type": "chart",
                "placeholder_title": "Revenue Performance",
                "ai_instructions": "Revenue chart with trend",
            },
            {
                "order": 4,
                "slide_type": "bullets",
                "placeholder_title": "Achievements",
                "ai_instructions": "Major wins this quarter",
            },
            {
                "order": 5,
                "slide_type": "bullets",
                "placeholder_title": "Challenges",
                "ai_instructions": "Obstacles faced",
            },
            {
                "order": 6,
                "slide_type": "timeline",
                "placeholder_title": "Next Quarter Goals",
                "ai_instructions": "Upcoming milestones",
            },
        ],
    },
    {
        "name": "Sales Proposal",
        "description": "Persuasive sales pitch for potential clients",
        "category": "business",
        "theme": "corporate",
        "tags": ["sales", "proposal", "client", "deal"],
        "difficulty_level": "beginner",
        "estimated_time": 10,
        "industry_tags": ['business', 'sales', 'b2b'],
        "popularity_score": 80,
        "slides": [
            {
                "order": 1,
                "slide_type": "title",
                "ai_instructions": "Client-focused title with value proposition",
            },
            {
                "order": 2,
                "slide_type": "content",
                "placeholder_title": "Understanding Your Needs",
                "ai_instructions": "Show you understand their challenges",
            },
            {
                "order": 3,
                "slide_type": "bullets",
                "placeholder_title": "Our Solution",
                "ai_instructions": "How we solve their specific problems",
            },
            {
                "order": 4,
                "slide_type": "stats",
                "placeholder_title": "Proven Results",
                "ai_instructions": "Key metrics and success stats",
            },
            {
                "order": 5,
                "slide_type": "comparison",
                "placeholder_title": "Why Choose Us",
                "ai_instructions": "Before/after or us vs alternatives",
            },
            {
                "order": 6,
                "slide_type": "quote",
                "ai_instructions": "Client testimonial",
            },
            {
                "order": 7,
                "slide_type": "bullets",
                "placeholder_title": "Investment & ROI",
                "ai_instructions": "Pricing and expected returns",
            },
            {
                "order": 8,
                "slide_type": "section",
                "placeholder_title": "Next Steps",
                "ai_instructions": "Clear call to action",
            },
        ],
    },
    {
        "name": "Product Launch",
        "description": "Announce and showcase a new product",
        "category": "marketing",
        "theme": "dark",
        "tags": ["product", "launch", "marketing", "announcement"],
        "difficulty_level": "intermediate",
        "estimated_time": 12,
        "industry_tags": ['marketing', 'product', 'tech'],
        "popularity_score": 90,
        "slides": [
            {
                "order": 1,
                "slide_type": "title",
                "ai_instructions": "Product name with exciting tagline",
            },
            {
                "order": 2,
                "slide_type": "content",
                "placeholder_title": "The Challenge",
                "ai_instructions": "Problem this product solves",
            },
            {
                "order": 3,
                "slide_type": "content",
                "placeholder_title": "Introducing...",
                "ai_instructions": "Product reveal with key value prop",
            },
            {
                "order": 4,
                "slide_type": "bullets",
                "placeholder_title": "Key Features",
                "ai_instructions": "Top 5 features",
            },
            {
                "order": 5,
                "slide_type": "comparison",
                "placeholder_title": "Before & After",
                "ai_instructions": "Life without vs with product",
            },
            {
                "order": 6,
                "slide_type": "stats",
                "placeholder_title": "Early Results",
                "ai_instructions": "Beta metrics or projections",
            },
            {
                "order": 7,
                "slide_type": "quote",
                "ai_instructions": "Customer testimonial or endorsement",
            },
            {
                "order": 8,
                "slide_type": "section",
                "placeholder_title": "Get Started",
                "ai_instructions": "CTA with availability info",
            },
        ],
    },
    {
        "name": "Course Introduction",
        "description": "Introduction to an educational course or workshop",
        "category": "education",
        "theme": "forest",
        "tags": ["course", "education", "training", "workshop"],
        "difficulty_level": "beginner",
        "estimated_time": 8,
        "industry_tags": ['education', 'training'],
        "popularity_score": 70,
        "slides": [
            {
                "order": 1,
                "slide_type": "title",
                "ai_instructions": "Course title and instructor",
            },
            {
                "order": 2,
                "slide_type": "bullets",
                "placeholder_title": "What You'll Learn",
                "ai_instructions": "Learning objectives",
            },
            {
                "order": 3,
                "slide_type": "timeline",
                "placeholder_title": "Course Outline",
                "ai_instructions": "Module breakdown",
            },
            {
                "order": 4,
                "slide_type": "content",
                "placeholder_title": "Prerequisites",
                "ai_instructions": "What students should know",
            },
            {
                "order": 5,
                "slide_type": "bullets",
                "placeholder_title": "Materials Needed",
                "ai_instructions": "Required tools/resources",
            },
            {
                "order": 6,
                "slide_type": "section",
                "placeholder_title": "Let's Begin!",
                "ai_instructions": "Motivational closing",
            },
        ],
    },
    {
        "name": "Research Presentation",
        "description": "Academic research findings presentation",
        "category": "education",
        "theme": "minimal",
        "tags": ["research", "academic", "thesis", "findings"],
        "difficulty_level": "advanced",
        "estimated_time": 20,
        "industry_tags": ['education', 'academic', 'research'],
        "popularity_score": 60,
        "slides": [
            {
                "order": 1,
                "slide_type": "title",
                "ai_instructions": "Research title and author/institution",
            },
            {
                "order": 2,
                "slide_type": "content",
                "placeholder_title": "Background",
                "ai_instructions": "Context and prior research",
            },
            {
                "order": 3,
                "slide_type": "bullets",
                "placeholder_title": "Research Questions",
                "ai_instructions": "Key questions being addressed",
            },
            {
                "order": 4,
                "slide_type": "content",
                "placeholder_title": "Methodology",
                "ai_instructions": "Research approach and methods",
            },
            {
                "order": 5,
                "slide_type": "chart",
                "placeholder_title": "Key Findings",
                "ai_instructions": "Data visualization of results",
            },
            {
                "order": 6,
                "slide_type": "stats",
                "placeholder_title": "Results Summary",
                "ai_instructions": "Key metrics and statistics",
            },
            {
                "order": 7,
                "slide_type": "bullets",
                "placeholder_title": "Conclusions",
                "ai_instructions": "Main takeaways",
            },
            {
                "order": 8,
                "slide_type": "section",
                "placeholder_title": "Questions?",
                "ai_instructions": "Contact info and references",
            },
        ],
    },
    {
        "name": "Technical Architecture",
        "description": "System design and architecture overview",
        "category": "technology",
        "theme": "terminal",
        "tags": ["architecture", "technical", "system", "engineering"],
        "difficulty_level": "advanced",
        "estimated_time": 18,
        "industry_tags": ['technology', 'software', 'engineering'],
        "popularity_score": 75,
        "slides": [
            {
                "order": 1,
                "slide_type": "title",
                "ai_instructions": "System name and version",
            },
            {
                "order": 2,
                "slide_type": "content",
                "placeholder_title": "Overview",
                "ai_instructions": "High-level system description",
            },
            {
                "order": 3,
                "slide_type": "bullets",
                "placeholder_title": "Components",
                "ai_instructions": "Key system components",
            },
            {
                "order": 4,
                "slide_type": "content",
                "placeholder_title": "Data Flow",
                "ai_instructions": "How data moves through system",
            },
            {
                "order": 5,
                "slide_type": "comparison",
                "placeholder_title": "Tech Stack",
                "ai_instructions": "Frontend vs Backend technologies",
            },
            {
                "order": 6,
                "slide_type": "bullets",
                "placeholder_title": "Security",
                "ai_instructions": "Security measures",
            },
            {
                "order": 7,
                "slide_type": "stats",
                "placeholder_title": "Performance",
                "ai_instructions": "Key performance metrics",
            },
            {
                "order": 8,
                "slide_type": "timeline",
                "placeholder_title": "Roadmap",
                "ai_instructions": "Planned improvements",
            },
        ],
    },
    {
        "name": "Sprint Review",
        "description": "Agile sprint review and demo",
        "category": "technology",
        "theme": "ai",
        "tags": ["agile", "sprint", "scrum", "demo"],
        "difficulty_level": "beginner",
        "estimated_time": 10,
        "industry_tags": ['technology', 'agile', 'software'],
        "popularity_score": 65,
        "slides": [
            {
                "order": 1,
                "slide_type": "title",
                "ai_instructions": "Sprint number and date range",
            },
            {
                "order": 2,
                "slide_type": "stats",
                "placeholder_title": "Sprint Metrics",
                "ai_instructions": "Story points, velocity, completion rate",
            },
            {
                "order": 3,
                "slide_type": "bullets",
                "placeholder_title": "Completed Stories",
                "ai_instructions": "User stories delivered",
            },
            {
                "order": 4,
                "slide_type": "content",
                "placeholder_title": "Demo Highlights",
                "ai_instructions": "Key features to demonstrate",
            },
            {
                "order": 5,
                "slide_type": "bullets",
                "placeholder_title": "Blockers & Challenges",
                "ai_instructions": "Issues encountered",
            },
            {
                "order": 6,
                "slide_type": "timeline",
                "placeholder_title": "Next Sprint",
                "ai_instructions": "Upcoming priorities",
            },
        ],
    },
    {
        "name": "Portfolio Showcase",
        "description": "Creative portfolio presentation",
        "category": "creative",
        "theme": "playful",
        "tags": ["portfolio", "creative", "showcase", "design"],
        "difficulty_level": "beginner",
        "estimated_time": 15,
        "industry_tags": ['creative', 'design', 'freelance'],
        "popularity_score": 70,
        "slides": [
            {
                "order": 1,
                "slide_type": "title",
                "ai_instructions": "Name and creative title",
            },
            {
                "order": 2,
                "slide_type": "content",
                "placeholder_title": "About Me",
                "ai_instructions": "Brief bio and philosophy",
            },
            {
                "order": 3,
                "slide_type": "bullets",
                "placeholder_title": "Skills",
                "ai_instructions": "Key competencies",
            },
            {
                "order": 4,
                "slide_type": "content",
                "placeholder_title": "Featured Project 1",
                "ai_instructions": "First project highlight",
            },
            {
                "order": 5,
                "slide_type": "content",
                "placeholder_title": "Featured Project 2",
                "ai_instructions": "Second project highlight",
            },
            {
                "order": 6,
                "slide_type": "content",
                "placeholder_title": "Featured Project 3",
                "ai_instructions": "Third project highlight",
                "is_required": False,
            },
            {
                "order": 7,
                "slide_type": "quote",
                "ai_instructions": "Client testimonial",
            },
            {
                "order": 8,
                "slide_type": "section",
                "placeholder_title": "Let's Connect",
                "ai_instructions": "Contact information",
            },
        ],
    },
    {
        "name": "Event Announcement",
        "description": "Promote an upcoming event",
        "category": "creative",
        "theme": "neobrutalism",
        "tags": ["event", "announcement", "conference", "meetup"],
        "difficulty_level": "beginner",
        "estimated_time": 8,
        "industry_tags": ['creative', 'marketing', 'events'],
        "popularity_score": 55,
        "slides": [
            {
                "order": 1,
                "slide_type": "title",
                "ai_instructions": "Event name with exciting tagline",
            },
            {
                "order": 2,
                "slide_type": "big_number",
                "placeholder_title": "Save the Date",
                "ai_instructions": "Date and location prominently displayed",
            },
            {
                "order": 3,
                "slide_type": "bullets",
                "placeholder_title": "What to Expect",
                "ai_instructions": "Event highlights and activities",
            },
            {
                "order": 4,
                "slide_type": "stats",
                "placeholder_title": "Speakers & Guests",
                "ai_instructions": "Notable attendees/speakers",
            },
            {
                "order": 5,
                "slide_type": "timeline",
                "placeholder_title": "Schedule",
                "ai_instructions": "Event agenda overview",
            },
            {
                "order": 6,
                "slide_type": "section",
                "placeholder_title": "Register Now",
                "ai_instructions": "CTA and registration info",
            },
        ],
    },
    {
        "name": "Personal Introduction",
        "description": "Introduce yourself professionally",
        "category": "personal",
        "theme": "magazine",
        "tags": ["introduction", "personal", "about", "bio"],
        "difficulty_level": "beginner",
        "estimated_time": 8,
        "industry_tags": ['personal', 'networking'],
        "popularity_score": 50,
        "slides": [
            {
                "order": 1,
                "slide_type": "title",
                "ai_instructions": "Name and professional title",
            },
            {
                "order": 2,
                "slide_type": "content",
                "placeholder_title": "My Story",
                "ai_instructions": "Brief personal/professional journey",
            },
            {
                "order": 3,
                "slide_type": "bullets",
                "placeholder_title": "What I Do",
                "ai_instructions": "Key skills and expertise",
            },
            {
                "order": 4,
                "slide_type": "stats",
                "placeholder_title": "By the Numbers",
                "ai_instructions": "Key achievements in numbers",
            },
            {
                "order": 5,
                "slide_type": "bullets",
                "placeholder_title": "Fun Facts",
                "ai_instructions": "Personal interests/hobbies",
                "is_required": False,
            },
            {
                "order": 6,
                "slide_type": "section",
                "placeholder_title": "Let's Connect",
                "ai_instructions": "Contact and social links",
            },
        ],
    },
    {
        "name": "Project Kickoff",
        "description": "Launch a new project with your team",
        "category": "business",
        "theme": "lavender",
        "tags": ["project", "kickoff", "team", "planning"],
        "difficulty_level": "beginner",
        "estimated_time": 10,
        "industry_tags": ['business', 'project-management'],
        "popularity_score": 60,
        "slides": [
            {
                "order": 1,
                "slide_type": "title",
                "ai_instructions": "Project name and tagline",
            },
            {
                "order": 2,
                "slide_type": "content",
                "placeholder_title": "Project Vision",
                "ai_instructions": "What we're building and why",
            },
            {
                "order": 3,
                "slide_type": "bullets",
                "placeholder_title": "Goals & Objectives",
                "ai_instructions": "Key success criteria",
            },
            {
                "order": 4,
                "slide_type": "stats",
                "placeholder_title": "The Team",
                "ai_instructions": "Team members and roles",
            },
            {
                "order": 5,
                "slide_type": "timeline",
                "placeholder_title": "Project Timeline",
                "ai_instructions": "Key milestones and deadlines",
            },
            {
                "order": 6,
                "slide_type": "bullets",
                "placeholder_title": "Success Metrics",
                "ai_instructions": "How we'll measure success",
            },
            {
                "order": 7,
                "slide_type": "section",
                "placeholder_title": "Let's Go!",
                "ai_instructions": "Next steps and call to action",
            },
        ],
    },
    # ==================== HEALTHCARE ====================
    {
        "name": "Patient Care Plan",
        "description": "Comprehensive patient care and treatment plan",
        "category": "healthcare",
        "theme": "ocean",
        "tags": ["healthcare", "patient-care", "medical", "treatment"],
        "difficulty_level": "intermediate",
        "estimated_time": 15,
        "industry_tags": ["healthcare", "medical", "nursing"],
        "popularity_score": 70,
        "slides": [
            {"order": 1, "slide_type": "title", "ai_instructions": "Patient name and care plan title"},
            {"order": 2, "slide_type": "content", "placeholder_title": "Patient Overview", "ai_instructions": "Demographics, chief complaint, medical history in 60-80 words"},
            {"order": 3, "slide_type": "bullets", "placeholder_title": "Diagnosis", "ai_instructions": "Primary and secondary diagnoses with ICD codes if applicable"},
            {"order": 4, "slide_type": "bullets", "placeholder_title": "Treatment Goals", "ai_instructions": "SMART goals for patient recovery/management"},
            {"order": 5, "slide_type": "content", "placeholder_title": "Care Plan", "ai_instructions": "Detailed treatment approach including medications, therapies, lifestyle modifications"},
            {"order": 6, "slide_type": "timeline", "placeholder_title": "Follow-up Schedule", "ai_instructions": "Timeline of appointments and checkpoints"},
        ],
    },
    {
        "name": "Medical Research Presentation",
        "description": "Clinical or medical research findings",
        "category": "healthcare",
        "theme": "minimal",
        "tags": ["research", "clinical", "medical", "study"],
        "difficulty_level": "advanced",
        "estimated_time": 25,
        "industry_tags": ["healthcare", "research", "academic"],
        "popularity_score": 65,
        "slides": [
            {"order": 1, "slide_type": "title", "ai_instructions": "Study title, PI name, institution"},
            {"order": 2, "slide_type": "content", "placeholder_title": "Background", "ai_instructions": "Clinical significance and prior research context"},
            {"order": 3, "slide_type": "bullets", "placeholder_title": "Objectives", "ai_instructions": "Primary and secondary research objectives"},
            {"order": 4, "slide_type": "content", "placeholder_title": "Methodology", "ai_instructions": "Study design, sample size, inclusion/exclusion criteria"},
            {"order": 5, "slide_type": "stats", "placeholder_title": "Results", "ai_instructions": "Key findings with statistical significance"},
            {"order": 6, "slide_type": "chart", "placeholder_title": "Data Visualization", "ai_instructions": "Primary outcome data"},
            {"order": 7, "slide_type": "bullets", "placeholder_title": "Clinical Implications", "ai_instructions": "How findings impact patient care"},
            {"order": 8, "slide_type": "section", "placeholder_title": "Conclusions", "ai_instructions": "Summary and future research directions"},
        ],
    },
    # ==================== FINANCE ====================
    {
        "name": "Investment Strategy",
        "description": "Investment thesis and portfolio strategy",
        "category": "finance",
        "theme": "corporate",
        "tags": ["investment", "portfolio", "strategy", "finance"],
        "difficulty_level": "advanced",
        "estimated_time": 20,
        "industry_tags": ["finance", "investment", "wealth-management"],
        "popularity_score": 80,
        "slides": [
            {"order": 1, "slide_type": "title", "ai_instructions": "Strategy name and investment period"},
            {"order": 2, "slide_type": "content", "placeholder_title": "Market Analysis", "ai_instructions": "Current market conditions and key drivers in 70-100 words"},
            {"order": 3, "slide_type": "bullets", "placeholder_title": "Investment Thesis", "ai_instructions": "Core assumptions and rationale for strategy"},
            {"order": 4, "slide_type": "chart", "placeholder_title": "Asset Allocation", "ai_instructions": "Portfolio distribution across asset classes"},
            {"order": 5, "slide_type": "stats", "placeholder_title": "Expected Returns", "ai_instructions": "Projected returns, risks, and time horizon"},
            {"order": 6, "slide_type": "comparison", "placeholder_title": "Risk Assessment", "ai_instructions": "Risk vs return profile compared to benchmarks"},
            {"order": 7, "slide_type": "timeline", "placeholder_title": "Implementation Plan", "ai_instructions": "Phased approach to deploying capital"},
        ],
    },
    {
        "name": "Financial Analysis Report",
        "description": "Company financial performance analysis",
        "category": "finance",
        "theme": "sunset",
        "tags": ["financial-analysis", "performance", "metrics", "reporting"],
        "difficulty_level": "intermediate",
        "estimated_time": 18,
        "industry_tags": ["finance", "accounting", "corporate"],
        "popularity_score": 75,
        "slides": [
            {"order": 1, "slide_type": "title", "ai_instructions": "Company name and reporting period"},
            {"order": 2, "slide_type": "stats", "placeholder_title": "Financial Highlights", "ai_instructions": "Revenue, profit, margins, key ratios"},
            {"order": 3, "slide_type": "chart", "placeholder_title": "Revenue Trends", "ai_instructions": "Multi-period revenue analysis"},
            {"order": 4, "slide_type": "comparison", "placeholder_title": "Profitability Analysis", "ai_instructions": "Gross margin, operating margin, net margin trends"},
            {"order": 5, "slide_type": "bullets", "placeholder_title": "Balance Sheet Strength", "ai_instructions": "Assets, liabilities, equity, working capital"},
            {"order": 6, "slide_type": "stats", "placeholder_title": "Cash Flow", "ai_instructions": "Operating, investing, financing cash flows"},
            {"order": 7, "slide_type": "bullets", "placeholder_title": "Key Insights", "ai_instructions": "Financial strengths, concerns, and recommendations"},
        ],
    },
    {
        "name": "Budget Planning",
        "description": "Annual or departmental budget plan",
        "category": "finance",
        "theme": "forest",
        "tags": ["budget", "planning", "forecast", "financial-planning"],
        "difficulty_level": "beginner",
        "estimated_time": 12,
        "industry_tags": ["finance", "corporate", "management"],
        "popularity_score": 85,
        "slides": [
            {"order": 1, "slide_type": "title", "ai_instructions": "Budget period and department/company name"},
            {"order": 2, "slide_type": "content", "placeholder_title": "Budget Overview", "ai_instructions": "Total budget, key priorities, strategic alignment"},
            {"order": 3, "slide_type": "chart", "placeholder_title": "Revenue Projections", "ai_instructions": "Expected income sources and amounts"},
            {"order": 4, "slide_type": "chart", "placeholder_title": "Expense Breakdown", "ai_instructions": "Major expense categories with percentages"},
            {"order": 5, "slide_type": "comparison", "placeholder_title": "YoY Comparison", "ai_instructions": "Current vs previous year budget"},
            {"order": 6, "slide_type": "bullets", "placeholder_title": "Key Assumptions", "ai_instructions": "Growth rates, cost increases, market conditions"},
            {"order": 7, "slide_type": "timeline", "placeholder_title": "Review Schedule", "ai_instructions": "Quarterly review and adjustment milestones"},
        ],
    },
    # ==================== SALES ====================
    {
        "name": "Sales Training",
        "description": "Sales methodology and best practices training",
        "category": "sales",
        "theme": "ai",
        "tags": ["sales-training", "methodology", "best-practices", "skills"],
        "difficulty_level": "beginner",
        "estimated_time": 14,
        "industry_tags": ["sales", "training", "business"],
        "popularity_score": 70,
        "slides": [
            {"order": 1, "slide_type": "title", "ai_instructions": "Training topic and session name"},
            {"order": 2, "slide_type": "bullets", "placeholder_title": "Learning Objectives", "ai_instructions": "What participants will learn and be able to do"},
            {"order": 3, "slide_type": "content", "placeholder_title": "Sales Process Overview", "ai_instructions": "Steps from prospecting to close in 60-80 words"},
            {"order": 4, "slide_type": "bullets", "placeholder_title": "Discovery Best Practices", "ai_instructions": "Key questions and listening techniques"},
            {"order": 5, "slide_type": "content", "placeholder_title": "Handling Objections", "ai_instructions": "Common objections and response frameworks"},
            {"order": 6, "slide_type": "comparison", "placeholder_title": "Do's and Don'ts", "ai_instructions": "Effective vs ineffective sales behaviors"},
            {"order": 7, "slide_type": "bullets", "placeholder_title": "Action Items", "ai_instructions": "Practice exercises and next steps"},
        ],
    },
    {
        "name": "Territory Planning",
        "description": "Sales territory strategy and planning",
        "category": "sales",
        "theme": "playful",
        "tags": ["territory", "planning", "strategy", "sales-ops"],
        "difficulty_level": "intermediate",
        "estimated_time": 16,
        "industry_tags": ["sales", "sales-operations", "management"],
        "popularity_score": 65,
        "slides": [
            {"order": 1, "slide_type": "title", "ai_instructions": "Territory name and planning period"},
            {"order": 2, "slide_type": "stats", "placeholder_title": "Territory Overview", "ai_instructions": "Account count, revenue potential, coverage"},
            {"order": 3, "slide_type": "chart", "placeholder_title": "Account Segmentation", "ai_instructions": "Breakdown by size, industry, or potential"},
            {"order": 4, "slide_type": "bullets", "placeholder_title": "Strategic Accounts", "ai_instructions": "Top opportunities and relationship status"},
            {"order": 5, "slide_type": "timeline", "placeholder_title": "Coverage Plan", "ai_instructions": "Quarterly account visit and engagement schedule"},
            {"order": 6, "slide_type": "stats", "placeholder_title": "Targets & Goals", "ai_instructions": "Quota, pipeline, activity metrics"},
            {"order": 7, "slide_type": "bullets", "placeholder_title": "Success Strategies", "ai_instructions": "Territory-specific tactics and resources needed"},
        ],
    },
    {
        "name": "Customer Success Review",
        "description": "Quarterly business review with customer",
        "category": "sales",
        "theme": "lavender",
        "tags": ["customer-success", "qbr", "account-management", "retention"],
        "difficulty_level": "intermediate",
        "estimated_time": 15,
        "industry_tags": ["sales", "customer-success", "account-management"],
        "popularity_score": 80,
        "slides": [
            {"order": 1, "slide_type": "title", "ai_instructions": "Customer name and review period"},
            {"order": 2, "slide_type": "stats", "placeholder_title": "Partnership Highlights", "ai_instructions": "Key metrics and wins since last review"},
            {"order": 3, "slide_type": "chart", "placeholder_title": "Usage & Adoption", "ai_instructions": "Product usage trends and user growth"},
            {"order": 4, "slide_type": "bullets", "placeholder_title": "Value Delivered", "ai_instructions": "ROI, outcomes achieved, business impact"},
            {"order": 5, "slide_type": "bullets", "placeholder_title": "Initiatives Delivered", "ai_instructions": "Features launched, support provided, training completed"},
            {"order": 6, "slide_type": "timeline", "placeholder_title": "Roadmap & Next Steps", "ai_instructions": "Upcoming features and collaboration opportunities"},
            {"order": 7, "slide_type": "section", "placeholder_title": "Discussion", "ai_instructions": "Open floor for feedback and questions"},
        ],
    },
    # ==================== NONPROFIT ====================
    {
        "name": "Fundraising Campaign",
        "description": "Nonprofit fundraising and donor pitch",
        "category": "nonprofit",
        "theme": "neobrutalism",
        "tags": ["fundraising", "nonprofit", "donation", "impact"],
        "difficulty_level": "beginner",
        "estimated_time": 12,
        "industry_tags": ["nonprofit", "fundraising", "charity"],
        "popularity_score": 75,
        "slides": [
            {"order": 1, "slide_type": "title", "ai_instructions": "Campaign name and organization"},
            {"order": 2, "slide_type": "content", "placeholder_title": "Our Mission", "ai_instructions": "Organization purpose and community served in 50-70 words"},
            {"order": 3, "slide_type": "stats", "placeholder_title": "The Need", "ai_instructions": "Problem statistics and urgency"},
            {"order": 4, "slide_type": "content", "placeholder_title": "Our Solution", "ai_instructions": "Programs and services addressing the need"},
            {"order": 5, "slide_type": "bullets", "placeholder_title": "Impact Stories", "ai_instructions": "Real beneficiary outcomes and testimonials"},
            {"order": 6, "slide_type": "stats", "placeholder_title": "Campaign Goal", "ai_instructions": "Fundraising target and allocation"},
            {"order": 7, "slide_type": "bullets", "placeholder_title": "How to Help", "ai_instructions": "Donation levels and volunteer opportunities"},
            {"order": 8, "slide_type": "section", "placeholder_title": "Join Us", "ai_instructions": "Call to action and contact info"},
        ],
    },
    {
        "name": "Impact Report",
        "description": "Annual nonprofit impact and outcomes report",
        "category": "nonprofit",
        "theme": "magazine",
        "tags": ["impact", "annual-report", "nonprofit", "outcomes"],
        "difficulty_level": "beginner",
        "estimated_time": 14,
        "industry_tags": ["nonprofit", "social-impact", "philanthropy"],
        "popularity_score": 70,
        "slides": [
            {"order": 1, "slide_type": "title", "ai_instructions": "Report year and organization name"},
            {"order": 2, "slide_type": "content", "placeholder_title": "Executive Summary", "ai_instructions": "Year highlights and overall impact in 80-100 words"},
            {"order": 3, "slide_type": "stats", "placeholder_title": "By the Numbers", "ai_instructions": "Key impact metrics - people served, programs delivered, etc"},
            {"order": 4, "slide_type": "bullets", "placeholder_title": "Major Achievements", "ai_instructions": "Top 5 accomplishments for the year"},
            {"order": 5, "slide_type": "quote", "placeholder_title": "Beneficiary Story", "ai_instructions": "Include testimonial from program participant with their name/attribution"},
            {"order": 6, "slide_type": "chart", "placeholder_title": "Financial Overview", "ai_instructions": "Revenue sources and program spending breakdown"},
            {"order": 7, "slide_type": "bullets", "placeholder_title": "Looking Ahead", "ai_instructions": "Goals and initiatives for next year"},
            {"order": 8, "slide_type": "section", "placeholder_title": "Thank You", "ai_instructions": "Gratitude to donors and supporters"},
        ],
    },
]


async def seed_templates(db) -> int:
    """
    Seed system templates into database.
    Returns count of templates created or updated.
    """
    from sqlalchemy import select, delete

    from packages.common.models.template import Template, TemplateSlide

    created = 0

    for template_data in SYSTEM_TEMPLATES:
        # Check if already exists
        query = select(Template).where(
            Template.name == template_data["name"],
            Template.is_system == True,  # noqa: E712
        )
        result = await db.execute(query)
        existing = result.scalar_one_or_none()

        if existing:
            # Delete existing template and its slides (cascade delete)
            await db.delete(existing)
            await db.flush()

        # Create template
        slides_data = template_data.pop("slides")
        template = Template(**template_data, is_system=True)

        for slide_data in slides_data:
            slide = TemplateSlide(**slide_data)
            template.slides.append(slide)

        db.add(template)
        created += 1

    await db.commit()
    return created
